### ISSUE TITLE
move imager data to the clean bucket

### ISSUE THREAD

**Issue by frolovsa** [NOAA-PSL/observation-archive#56]
Move this nasa data to the clean bucket

I have moved the following files to s3://na-stage.us-east-2.noaa-nasa-share/nasa/reanalysis/
as requested.
TMI,
AIRS
amsua-aqua
amsr2
gmi
amsre
avhrr_repro

**Comment by jrknezha** [comment]
@frolovsa I don't see any data in the bucket related to AIRS is that missing? 

additionally, are these the folder names we want in the clean bucket? should it be just avhrr?

**Comment by frolovsa** [comment]
airs is in here aqua_disc/bufr/airs/ and it should go to airs/nasa/aqua_disc
aqua_disc/bufr/amsu/ should go to amsua/nasa/aqua/
AVHRR_repro ->avhrr/nasa/21cr_repro/
TRMM -> trmm/nasa/tmi
amsr2 -> amsr2/nasa/
amsre -> amsre/nasa/
gmi_v7->gmi/nasa/gmi_v7/

i hope this covers it

**Comment by jrknezha** [comment]
ahh I didn't get deep enough. thank you. and this should be all I need for it!
